// rg-vendored.bin (generated by vendorRipgrep.ts, see runRipgrep.ts) is a raw binary asset,
// not a JS/TS module — declare it so `with { type: "file" }` imports of it typecheck.
declare module "*.bin" {
  const path: string;
  export default path;
}
